package jm.task.core.jdbc.dao;

import jm.task.core.jdbc.model.User;
import jm.task.core.jdbc.util.Util;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

public class UserDaoJDBCImpl implements UserDao {


    public UserDaoJDBCImpl() {

    }

    public void createUsersTable() {
        try (Connection connection = Util.connection()) {
            Statement statement = connection.createStatement();
            String SQL = "CREATE TABLE IF NOT EXISTS Users (id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,name VARCHAR(50),lastName VARCHAR(50), age SMALLINT)";
            statement.executeUpdate(SQL);
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }

    }

    public void dropUsersTable() {
        try (Connection connection = Util.connection()) {
            Statement statement = connection.createStatement();
            String SQL = "DROP TABLE IF EXISTS Users";
            statement.executeUpdate(SQL);
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public void saveUser(String name, String lastName, byte age) {
        try (Connection connection = Util.connection()) {
            Statement statement = connection.createStatement();
            String SQL = "INSERT INTO Users (name, lastName, age) VALUES ( '" + name + "', '" + lastName + "', " + age + ")";
            statement.executeUpdate(SQL);
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public void removeUserById(long id) {
        try (Connection connection = Util.connection()){
            Statement statement = connection.createStatement();
            String SQL = "DELETE FROM Users WHERE id = " + id;
            statement.executeUpdate(SQL);
        } catch (SQLException e){
            throw new RuntimeException();
        }
    }

    public List<User> getAllUsers() {
        List<User> userList = new ArrayList<>();
        try (Connection connection = Util.connection();){
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery("SELECT * FROM Users");
            while (resultSet.next()){
                User user = new User();

                user.setId(resultSet.getLong("id"));
                user.setName(resultSet.getString("name"));
                user.setLastName(resultSet.getString("lastName"));
                user.setAge(resultSet.getByte("age"));

                userList.add(user);
            }
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
        return userList;
    }

    public void cleanUsersTable() {
        try (Connection connection = Util.connection();){
            Statement statement = connection.createStatement();
            String SQL = "TRUNCATE TABLE Users";
            statement.executeUpdate(SQL);
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }
}
